### ISSUE TITLE
npm run windows won't work

### ISSUE THREAD

**Issue by f8ttyc8t** [egoist/eme#104]
Thank you for sharing this great too!

Unfortunately Im not able to build windows version (exe).
Issuing "npm run windows" returns error below (using Windows 10 x64, Node version 7.2.1):

> d:\eme-dev>npm run windows
> eme@ windows d:\\eme-dev
> node tasks/build.js windows
> 
> Downloading electron-v1.4.12-win32-ia32.zip
> [============================================>] 100.0% of 44.03 MB (4.5
> Packaging app for platform win32 ia32 using electron v1.4.12
> dist\EME-win32-ia32
> 
> zip error: Invalid command arguments (short option 'y' not supported)

Any ideas how to solve that?

**Comment by egoist** [comment]
eh, you can just ignore the `zip` error, it's successfully packaged already ;)

**Comment by f8ttyc8t** [comment]
Uhm - embarrassing, didn't check that!

Thank you very much!

**Comment by egoist** [comment]
Never mind, I would update the script to support `zip` on windows later.
