### ISSUE TITLE
Code blocks lose background color in exported PDF

### ISSUE THREAD

**Issue by krissrex** [egoist/eme#106]
Bug: exported PDF does not keep the background color for `code blocks like this`.  
Expected: PDF has colored background like in EME preview.  

Left: Editor preview  
Right: exported PDF

![image](https://cloud.githubusercontent.com/assets/7364831/21298955/0b9cce76-c597-11e6-9633-2fe0003b6d10.png)

My version info:  
Windows
![image](https://cloud.githubusercontent.com/assets/7364831/21298923/b8324626-c596-11e6-9d15-af3dc132cdde.png)

**Comment by krissrex** [comment]
The same happens if you attempt to print a page as PDF with Chrome, and do not have "Background graphics" checked.

**Comment by egoist** [comment]
I guess it's because the background color is too light? maybe darker background would be print.

**Comment by krissrex** [comment]
They are not too light. 
I managed to fix it by adding a line to the body css:

`eme/app/vendor/css/print.css`:
```css
body {
  margin: 0;
  -webkit-print-color-adjust: exact;
}
```

**Comment by egoist** [comment]
oh thanks for your tip!
