### ISSUE TITLE
Key for character ` has a key binding

### ISSUE THREAD

**Issue by krissrex** [egoist/eme#107]
Bug: \` changes tabs on Norwegian keyboard
Expected: \` should only type the symbol \`

When more than one tab is open, pressing \` will change tabs on a Norwegian keyboard.

The key is to the left of backspace, and accessed with `SHIFT` pressed.
![norwegian keyboard](https://upload.wikimedia.org/wikipedia/en/c/c9/Keyboard_Layout_Norwegian.png)

**Comment by krissrex** [comment]
This is the shortcut that is being triggered: https://github.com/egoist/eme/blob/dev/src/components/header.vue#L239

```javascript
 Mousetrap.bindGlobal(`${cmdOrCtrl}+shift+[`, () => {
    if (this.tabs.length < 2) return
    const index = getLeftTabIndex(this.tabs.length, this.currentTabIndex)
    this.setCurrentTab(index)
})
```

I guess Mousetrap doesn't change bindings for different keyboard layouts.

**Comment by egoist** [comment]
I still don't get why `shift+\`` would trigger the shortcut

**Comment by krissrex** [comment]
The shortcut should be `ctrl`, but it uses `control`. I will push the fix soon. Mousetrap still registers `` ` `` as `[`, but it's not a big problem now.
