### ISSUE TITLE
Canceling unsaved-dialog still closes EME

### ISSUE THREAD

**Issue by krissrex** [egoist/eme#109]
Bug: Clicking cancel will exit EME
Expected: EME should not close.

Reproduce:
1. Open EME and type in some text
2. Click the X to close EME
3. When the dialog `Do you want to save the changes you made to untitled?` comes, click `Cancel` instead of `Save` or `Don't Save`
4. Now it still closes EME, without saving

![image](https://cloud.githubusercontent.com/assets/7364831/21343727/6ca1fc62-c698-11e6-9c47-74288ffad5a4.png)

**Comment by egoist** [comment]
weird, changing `remote.dialog.showMessageBox(option)` to async version `remote.dialog.showMessageBox(options, callback)` could fix this
