### ISSUE TITLE
Add katex usage to Wiki

### ISSUE THREAD

**Issue by krissrex** [egoist/eme#111]
It is not clear how to use the math typesetting.  
I suggest informing about it in either the Readme or in the Wiki.

The [Readme](https://github.com/waylonflinn/markdown-it-katex/blob/master/README.md#examples) at markdown-it-katex has examples for usage:

```md
$\sqrt{3x-1}+(1+x)^2$
```

```
$$\begin{array}{c}

\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &
= \frac{4\pi}{c}\vec{\mathbf{j}}    \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\

\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\

\nabla \cdot \vec{\mathbf{B}} & = 0

\end{array}$$
```

**Comment by egoist** [comment]
Added https://github.com/egoist/eme/wiki/Math-Typesetting and the wiki now is also writable for everyone now.
