### ISSUE TITLE
0.13.0 在 windows 端白屏

### ISSUE THREAD

**Issue by refparo** [egoist/eme#122]
![default](https://cloud.githubusercontent.com/assets/13145126/22458458/93a61c34-e7d7-11e6-874e-667db89d0c95.png)

**Comment by egoist** [comment]
貌似是忘了执行 npm run build 😅

**Comment by refparo** [comment]
这个都能忘 😂

**Comment by egoist** [comment]
我的 PC 慢的要死，是台已废弃的电脑 😂

**Comment by fengT-T** [comment]
linux的deb包也白屏了。。。。。@_@

**Comment by fengT-T** [comment]
@egoist

**Comment by elite-sheep** [comment]
@fengT-T Fixed, please download the latest version.
