### ISSUE TITLE
EME opens, but the whole screen is blank

### ISSUE THREAD

**Issue by vaporwavie** [egoist/eme#123]
Just installed the latest EME version available (0.13.0). When it starts, I got nothing but a blank screen. And that's it :(

<b>Screenshot</b>
![sub](http://i.imgur.com/HUfWfRE.png)

**Comment by magicknight** [comment]
The official build seems to have problem under ubuntu. I have my build uploaded:
https://goo.gl/grlZz8
This one works fine on ubuntu 16.04

**Comment by vaporwavie** [comment]
Thank you!
