### ISSUE TITLE
Latex "vector" symbol won't show (Version 0.12.0)

### ISSUE THREAD

**Issue by ricynlee** [egoist/eme#124]
![image](https://cloud.githubusercontent.com/assets/19217657/23735270/85ff3692-04bf-11e7-979b-e61193d8e844.png)

On Windows 10.

In the preview panel, `$\vec{a}$` is displayed as an *a* without an arrow above it.
But the exported PDF looks perfect.

There are no such problems with similar symbols like `$\bar{u}$`.

> 作者是个中国人，我还纠结了半天英文怎么翻译。

**Comment by elite-sheep** [comment]
I tried on the latest version on Mac. It looks good now. Do you still have this issue?

**Comment by ricynlee** [comment]
It does appear good now, for both real-time display and exported PDF doc. Thank you for the great job!

BTW could you consider adding a pre-built binary release for Windows? For many, it's really great to have your app in our daily working environment, mostly on Windows PCs. Following readme - which seems outdated - I failed to build it for Windows.
