### ISSUE TITLE
Why deprecated?

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/eme#135]
This is one of my favorite programs.

**Comment by egoist** [comment]
cuz I no longer have time to maintain it (currently)😅

**Comment by IonicaBizau** [comment]
@egoist As long you accept pull requests, it should be fine.

I don't even use the latest version, but I'm still in awe of it. Haha! :grin:

**Comment by egoist** [comment]
ah true, that's kinda confusing. removed *deprecated* cuz I believe I will come back to this project one day 😆

**Comment by IonicaBizau** [comment]
@egoist :rocket:
