### ISSUE TITLE
EME基础功能做的这么好,一年不更新了,不觉得遗憾后悔吗

### ISSUE THREAD

**Issue by ricynlee** [egoist/eme#138]
我要安安静静的做个用户~

**Comment by ricynlee** [comment]
Hi @Aaron19960821 , I opened this issue to ask for updates. As you're already updating EME, please resolve it.

**Comment by elite-sheep** [comment]
@ricynlee Thanks for messaging. I decided to support this project because I wrote course reports with this app when I was in University and I do not let it just die. I will try to fix more bugs, come up with new feature specs(New Dark Mode, Diagram support) in the future.
