### ISSUE TITLE
Unable to do anything

### ISSUE THREAD

**Issue by nottelmo** [egoist/eme#139]
Running **Arch Linux 64-bit**.

I have downloaded and extracted the tar file.
I am unable to create, change, write or save anything.
Running it with the terminal creates no output.

The only things I am able to do are:
- Toggle Developer Tools
- Toggle Fullscreen
- Check for updates
- Read About

**Comment by robeartoe** [comment]
I've had the same problem with the current version of eme. Try using the previous version of eme, and it should work. I'm running Elementary Linux 64-bit. 
I've had this same problem on my mac too with this version.

**Comment by elite-sheep** [comment]
I fix this issue and publish a new release.
https://github.com/Aaron19960821/eme/releases/tag/v0.13.1

**Comment by elite-sheep** [comment]
@nottelmo @robeartoe We have published a new version v0.15.0 and fix this issue. Feel free to download and get a try if you are still using EME. Thanks :D
