### ISSUE TITLE
Strange Counting

### ISSUE THREAD

**Issue by rajlego** [egoist/eme#154]
![Screen Shot 2020-03-23 at 6 40 52 PM](https://user-images.githubusercontent.com/5921902/77320037-dc017a00-6d35-11ea-911f-18b2960fde04.png)
I have no idea why this happens. It displays fine in browser with docsify but the previous for some screws up counting.

**Comment by elite-sheep** [comment]
@rajlego I will take a look on this issue, thanks for reporting.
BTW, which version and platform are you using?

**Comment by elite-sheep** [comment]
@rajlego I made some investigation, it seems that this is not our bug. Please refer this:
https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list
You may fix it by using 4 spaces as indent.
