### ISSUE TITLE
Official website not working

### ISSUE THREAD

**Issue by brunossn** [egoist/eme#156]
The official project website (https://eme.moe/) is redirecting to a wood business

![Captura de tela de 2020-05-01 22-11-46](https://user-images.githubusercontent.com/1033649/80851549-d468a700-8bf8-11ea-8e54-62abdfc32b70.png)

**Comment by elite-sheep** [comment]
This website should be built up by @egoist. Do you know the current status of this website?

**Comment by egoist** [comment]
updated https://egoist.sh/eme
