### ISSUE TITLE
image can not render

### ISSUE THREAD

**Issue by nicreals** [egoist/eme#22]
![image](https://cloud.githubusercontent.com/assets/8947175/17657208/cb7f67b4-62f3-11e6-9874-2d4d8b7a1b9d.png)
the image file patch is correct and this image can be rendered in other markdown editor but it does not works in EME.

**Comment by egoist** [comment]
Yes, it's because the `current working directly` of the file is set to the `app path`, so relative path won't work.

It would be fixed in the next release. Thx for reporting. 👍🏻
