### ISSUE TITLE
自定义 Tab 宽度

### ISSUE THREAD

**Issue by yiding-he** [egoist/eme#28]
我发现 EME 缺省 Tab 宽度为 2 字符，且找不到地方修改。希望能：
1、自定义 Tab 宽度；
2、允许使用空格代替 Tab，即按下 Tab 键时用多个空格来代替。

**Comment by egoist** [comment]
我觉得有必要加一个偏好设置的窗口了。

**Comment by djyde** [comment]
所以应该要像 atom/vs code 这样用 config 文件控制样式。。

**Comment by egoist** [comment]
@djyde Atom 是有界面的吧 😅

**Comment by djyde** [comment]
@egoist 哦是哦，太久没用了

**Comment by yiding-he** [comment]
设置界面不重要，如果一定打算做的话，先在配置文件里面实现了吧。

**Comment by egoist** [comment]
Closed by https://github.com/egoist/eme/pull/81
