### ISSUE TITLE
Provide Linux Release Packages

### ISSUE THREAD

**Issue by timofurrer** [egoist/eme#30]
Provide release packages for Linux distributions. E.g `.deb` and `.rpm` files.

**Comment by egoist** [comment]
Sure, I will publish the linux package today after some tests, today.

**Comment by egoist** [comment]
Hi, the linux(.deb) build is available now 😅 https://github.com/egoist/eme/releases/tag/v0.7.0

**Comment by michaelimfeld** [comment]
Hi

It seems that the `maintainer` entry is missing in the debian/control file:
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 44450 package 'eme':
 missing maintainer
```

**Comment by egoist** [comment]
[v0.8.0](https://github.com/egoist/eme/releases/tag/v0.8.0) fixed the `maintainer` issue.
