### ISSUE TITLE
保存时选择Save，然后在另存为窗口中取消会导致EME无法关闭

### ISSUE THREAD

**Issue by Problem233** [egoist/eme#38]
![step1](https://cloud.githubusercontent.com/assets/13145126/17762476/878589d8-6543-11e6-8f72-11380b71c070.png)
![step2](https://cloud.githubusercontent.com/assets/13145126/17762473/87804e28-6543-11e6-8ea1-92975573153d.png)
![step3](https://cloud.githubusercontent.com/assets/13145126/17762474/8782bb86-6543-11e6-9fcc-54b5fdbe87b4.png)
![error](https://cloud.githubusercontent.com/assets/13145126/17762475/87857650-6543-11e6-86e7-2cc2c92b4470.png)
此时就会无法关闭EME
@egoist

**Comment by Problem233** [comment]
:eyes: + :star:
:heart:

**Comment by egoist** [comment]
无法关闭是点窗口的 x 关不掉吗

**Comment by Problem233** [comment]
是的，只能到任务管理器里强关

**Comment by Problem233** [comment]
而且也无法进行任何别的操作了
