### ISSUE TITLE
Dropdown list to show all opened files

### ISSUE THREAD

**Issue by egoist** [egoist/eme#41]
It looks like:

<img width="266" alt="2016-08-18 5 04 30" src="https://cloud.githubusercontent.com/assets/8784712/17768284/ee0e538e-6565-11e6-81c2-3bb31e9a5388.png">

**Comment by Perkovec** [comment]
@egoist what this is better than tabs?

**Comment by egoist** [comment]
it's not going to replace tab, sometimes there're too many tabs to display, so we can see and switch tab in the dropdown list. Isn't it the same way in sublime text?

**Comment by Perkovec** [comment]
@egoist then first need to do this #43

**Comment by egoist** [comment]
closed, replaced this with a button to toggle preference pane
