### ISSUE TITLE
一个奇怪的使关闭标签页按钮消失的bug

### ISSUE THREAD

**Issue by Problem233** [egoist/eme#45]
![gif2](https://cloud.githubusercontent.com/assets/13145126/17800710/0676582e-6618-11e6-8791-8b625d2c41a0.gif)
一开始是偶然出现这个bug，后来就很难重现了。
重现方法：用鼠标在标签栏上一边移动一边狂点
@egoist

**Comment by Problem233** [comment]
补充：出现这个bug之后再次用鼠标在标签栏上一边移动一边狂点会恢复正常 :sweat_smile:

**Comment by egoist** [comment]
好难，重现不了 😂

**Comment by Problem233** [comment]
:joy: 那就算了吧 :joy: :joy:
我这样找bug会不会不太好 :joy:

**Comment by egoist** [comment]
啊，我在 ubuntu 上稍微点了几下就重现了。。

**Comment by egoist** [comment]
把 tab 拖到不是 tab 的地方放下也是这效果

**Comment by Problem233** [comment]
发现恢复的方法就是把tab换一下位置

**Comment by egoist** [comment]
这是个 bug，没有处理拖到其它地方的情况

**Comment by egoist** [comment]
closed by https://github.com/egoist/eme/commit/5dfa98d0d77c394aff25263b2aaa970470a17630
