### ISSUE TITLE
Missing maintainer

### ISSUE THREAD

**Issue by lelufg** [egoist/eme#61]
Here's what I got every time I update or deal with dpkg. I found that this might be a bug, since the eme's packages returns "Missing maintainer" error. It doesn't affect the package itself, tough.

`dpkg: warning: parsing file '/var/lib/dpkg/status' near line 39968 package 'eme':
 missing maintainer`

**Comment by egoist** [comment]
Sorry for this, a new release coming soon.

**Comment by egoist** [comment]
Fixed by https://github.com/egoist/eme/releases/tag/v0.8.0
