### ISSUE TITLE
#45 的问题在 0.8.0 版本中 仍然存在

### ISSUE THREAD

**Issue by Problem233** [egoist/eme#64]
把标签页拖动到标签栏以外的地方还是会导致关闭标签按钮消失

**Comment by egoist** [comment]
我这儿没问题 =.=

**Comment by Problem233** [comment]
我拖动到了下方文字区域这个问题就又出现了。。
我保证我用的是0.8.0版本

**Comment by egoist** [comment]
![gif](http://g.recordit.co/ygMs3hXJlu.gif) 😅

**Comment by Problem233** [comment]
为什么我在windows平台还是有这个问题……

**Comment by Problem233** [comment]
你发布的0.8.0版本windows包明明就是0.7.0版本的啊、、

**Comment by egoist** [comment]
好了，我重新上传了 0.8 的 windows 版本 😂

**Comment by Problem233** [comment]
:joy:
