### ISSUE TITLE
Cyrillic is not counted by word counter

### ISSUE THREAD

**Issue by Perkovec** [egoist/eme#69]
![image](https://cloud.githubusercontent.com/assets/7426664/18007427/b9235528-6bac-11e6-98bd-0303ffd37133.png)

**Comment by egoist** [comment]
seems https://github.com/yuehu/word-count does not support cyrillic, maybe switch to https://github.com/jonschlinkert/wordcount ?

**Comment by Perkovec** [comment]
#70
