### ISSUE TITLE
希望加入AppImage格式的release

### ISSUE THREAD

**Issue by chih7** [egoist/eme#76]
目前 eme 几乎不存在于所有 Linux 发行版的源中，[上游](https://github.com/egoist/eme)release也只支持deb的包，在这种情况下，[AppImage](http://appimage.org/) 是一个很好的选择，它有以下特性：

> Distribute your desktop Linux application in the AppImage format and win users running all common Linux distributions. Package once and run everywhere. Reach users on all major desktop distributions.

> Download an application, make it executable, and run! No need to install. No system libraries or system preferences are altered. Can also run in a sandbox like Firejail.

electron 打包成 AppImage 也非常简单，根据这个[方法](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) 可自动完成。

**Comment by egoist** [comment]
这个需要 code signing 吗

**Comment by chih7** [comment]
不签名应该也没什么问题。
