### ISSUE TITLE
Change the Presentation mode image and text

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/eme#77]
I'd suggest not using bad images and text in the last section of the page: https://eme.moe

---

@egoist I really like the project and the UI & UX. It's an amazing editor. Keep up the good work! ✨

**Comment by egoist** [comment]
😂 Thanks for the suggestion, I would update it later, don't even know what I was thinking then.

**Comment by IonicaBizau** [comment]
@egoist 😄

**Comment by IonicaBizau** [comment]
@egoist Thanks! I'll probably share it! 😁 

To make my point clearer: I'm strongly against such things. There is a lot of immorality around us and we have to help with what we can. 😄
