### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/eme#78]
Would be cool to have a dark mode. 😁

**Comment by IonicaBizau** [comment]
:bulb: Tip: I currently invert my monitor colors while using EME in fullscreen mode. Not bad. :joy:

**Comment by egoist** [comment]
Just tried to make some `dark` styling 😅

![2016-09-23 1 53 42](https://cloud.githubusercontent.com/assets/8784712/18759766/a2e01a46-8130-11e6-815b-f51447356e58.png)

**Comment by IonicaBizau** [comment]
@egoist That's cute! ✨

**Comment by IonicaBizau** [comment]
🎉
