### ISSUE TITLE
Can't export as PDF

### ISSUE THREAD

**Issue by cngzblank** [egoist/eme#80]
I can click this button,and EME pops the save dialogue,but when i click save button,no files create.I can't find my pdf file in disk.

**Comment by egoist** [comment]
Can you give a repro steps?

**Comment by koho** [comment]
ME TOO!

**Comment by awhitehouse104** [comment]
Somewhere it's losing the backslashes in the path and failing silently. Probably with ipcRenderer.send('pdf-window-ready', ...) as it will serialize arguments

**Comment by Viridovics** [comment]
I downloaded Version 0.10.0 for windows from https://github.com/egoist/eme/releases.
I'm using Windows 8.1 (v 6.3.9600). 

Export to PDF doesn't work. Reprostep looks like as @cngzblank reprostep.
