### ISSUE TITLE
3 level lists get red highlighting

### ISSUE THREAD

**Issue by hgezim** [egoist/eme#82]
The last items here end up red in syntax highlighter in markdown view.
- `Logged in`
  - source: blah
  - description: blue blah
    - first
    - second << this ends up red
    - third << so does this

**Comment by egoist** [comment]
What color it is supposed to be?

**Comment by hgezim** [comment]
@egoist You rock!

So the second, third, etc. items are red for no good reason while the first item is black:

<img width="521" alt="untitled___-_eme_and_3_level_lists_get_red_highlighting_ _issue__82_ _egoist_eme" src="https://cloud.githubusercontent.com/assets/124675/18757094/af04aa16-80af-11e6-80df-90b46b01df3c.png">

**Comment by egoist** [comment]
Ok, I got this.

**Comment by egoist** [comment]
<img width="387" alt="2016-11-29 5 10 38" src="https://cloud.githubusercontent.com/assets/8784712/20703489/c935cce4-b656-11e6-8b2b-ded67e33ad9c.png">

Seems the problem is gone? I haven't made any change 😃

**Comment by hgezim** [comment]
That's my favourite type of fix: effortless :-)
