### ISSUE TITLE
Happy to see this on SO

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/eme#95]
@egoist Just in case you don't know it. I was happy to see in the sidebar. :grin: 

![screenshot from 2016-11-24 11-09-08](https://cloud.githubusercontent.com/assets/2864371/20592515/9bad6bb6-b236-11e6-8558-89d99dc26965.png)

**Comment by egoist** [comment]
Thanks for letting me know, I should find some time to improve the logo/icon too 😆

**Comment by IonicaBizau** [comment]
I like it. Maybe you can make it to smile instead of being sad, by flipping the mouth. :joy:
