### ISSUE TITLE
Table assistance functions

### ISSUE THREAD

**Issue by JayAndCatchFire** [egoist/eme#99]
I deal with tables a lot in my markdown files, but tables are cumbersome to work with by hand in markdown.  I'd really appreciate some functionality to assist in common actions like creating a new table, adding and removing rows, and adding and removing columns.  Being able to justify the contents of cells would be nice, too.

**Comment by hexpunk** [comment]
I'm closing this issue as this repository hasn't seen activity in more than one year.
